In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "AirQualityData.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "khushikyad001/air-quality-data",
  file_path,
)

print("First 5 records:", df.head())

<ipython-input-35-90db47b8811b>:10: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df = kagglehub.load_dataset(

First 5 records:          Date   Time    CO(GT)     NOx(GT)     NO2(GT)      O3(GT)    SO2(GT)  \
0  2024-01-01  00:00  3.807947  172.026768  144.333317  118.120832   1.215679
1  2024-01-01  01:00  9.512072  241.824266  137.769318   15.325830   1.016178
2  2024-01-01  02:00  7.346740  228.288118   20.055086   44.377036  24.140910
3  2024-01-01  03:00  6.026719   47.016072  184.591909  139.488603   2.435392
4  2024-01-01  04:00  1.644585   45.625591  114.125968   95.634768  48.752095

        PM2.5        PM10  Temperature  ...  WindDirection  CO_NOx_Ratio  \
0  147.349671  208.803124    28.564580  ...     209.984267      0.022008
1   40.979839  145.595579     6.793192  ...     319.534890      0.039173
2   72.594740   26.155000    24.436552  ...     274.644300      0.032042
3  134.339724  276.367944    26.463951  ...     312.266023      0.125515
4   99.007422  294.295449    10.530331  ...      21.392120      0.035272

   NOx_NO2_Ratio  Temp_Humidity_Index  AirQualityIndex    CO_MA3     NO2_MA3  \
0       1.183671             3.541778       343.353046  3.807947  144.333317
1       1.742635             0.727989       206.282028  6.660009  141.051317
2      10.842422             7.378322       140.170920  6.888920  100.719240
3       0.253330            21.684266       307.928588  7.628510  114.138771
4       0.396310             9.627596       370.134556  5.006015  106.257654

       O3_MA3  DayOfWeek  Hour
0  118.120832          0     0
1   66.723331          0     1
2   59.274566          0     2
3   66.397156          0     3
4   93.166802          0     4

[5 rows x 23 columns]

In [ ]:
df.head()

,Date,Time,CO(GT),NOx(GT),NO2(GT),O3(GT),SO2(GT),PM2.5,PM10,Temperature,...,WindDirection,CO_NOx_Ratio,NOx_NO2_Ratio,Temp_Humidity_Index,AirQualityIndex,CO_MA3,NO2_MA3,O3_MA3,DayOfWeek,Hour
0,2024-01-01,00:00,3.807947,172.026768,144.333317,118.120832,1.215679,147.349671,208.803124,28.564580,...,209.984267,0.022008,1.183671,3.541778,343.353046,3.807947,144.333317,118.120832,0,0
1,2024-01-01,01:00,9.512072,241.824266,137.769318,15.325830,1.016178,40.979839,145.595579,6.793192,...,319.534890,0.039173,1.742635,0.727989,206.282028,6.660009,141.051317,66.723331,0,1
2,2024-01-01,02:00,7.346740,228.288118,20.055086,44.377036,24.140910,72.594740,26.155000,24.436552,...,274.644300,0.032042,10.842422,7.378322,140.170920,6.888920,100.719240,59.274566,0,2
3,2024-01-01,03:00,6.026719,47.016072,184.591909,139.488603,2.435392,134.339724,276.367944,26.463951,...,312.266023,0.125515,0.253330,21.684266,307.928588,7.628510,114.138771,66.397156,0,3
4,2024-01-01,04:00,1.644585,45.625591,114.125968,95.634768,48.752095,99.007422,294.295449,10.530331,...,21.392120,0.035272,0.396310,9.627596,370.134556,5.006015,106.257654,93.166802,0,4

In [ ]:
df.isnull().sum()

Date                   0
Time                   0
CO(GT)                 0
NOx(GT)                0
NO2(GT)                0
O3(GT)                 0
SO2(GT)                0
PM2.5                  0
PM10                   0
Temperature            0
Humidity               0
Pressure               0
WindSpeed              0
WindDirection          0
CO_NOx_Ratio           0
NOx_NO2_Ratio          0
Temp_Humidity_Index    0
AirQualityIndex        0
CO_MA3                 0
NO2_MA3                0
O3_MA3                 0
DayOfWeek              0
Hour                   0
dtype: int64